# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10c9667ef37fa6e8d02d996ffd3207e44ec79141d1f0846d404b6d2b37b71bfb79e8d8ff3cf3b8678fbedaae0d6bac2432623072ef5d5adb53eeb2b2ea4261b0

test:
  secret_key_base: 040203053b1e240240ab3298451ba836e88599ef0f06d3de527a9a0b9fe176ef013de79245dda0325a6be7cda168fc1118eb2c59d15bbf7245d184339685ccaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
